config/routes.rb
FirstApp::Application.routes.draw do
  
  resources :users
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :activities, :only => [:create, :destroy, :allactivities]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

resources :pages  
  
  match '/about',   :to => 'pages#about'
  match '/home',    :to => 'pages#home'
  match '/signout',   :to => 'pages#signout'
  match '/myteam',   :to => 'pages#myteam'
 
  match '/help',    :to => 'pages#help'
   match '/contact', :to => 'pages#contact'
  match '/myaccount', :to => 'pages#myaccount'
  

  get "pages/signout"

  
  
  
  
  resources :users
  get "users/show"
  match '/signup',  :to => 'users#new'
  match '/allusers',  :to => 'users#allusers'
  
  
  
  

   root :to => "pages#home"

end

app/views/pages/Copy of home.html.erb
<p>

        <!-- Creat new Activity -->   
   
     <% if signed_in? %>
      <table class="front" summary="For signed-in users">
        <tr>
        <td class="main">
          <h1 class="activity">Add new tivit</h1>
          <%= render 'shared/activity_form' %>
        
        
        <!-- Display Current Activities -->   
      
        <% unless current_user.activities.empty? %>
                <table class="activities" summary="User tasks">
                    <%= render current_user.activities %>
                </table>
        
        <% end %>
        </td>
        
        
        
        
        
        <td class="sidebar round">
          <%= render 'shared/user_info' %>
        </td>
    </tr>
  </table>
     <% else %>
        <%= link_to "Sign in", signin_path %>
     
        <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
     <% end %>

</p>

app/views/pages/Oldactivities.html.erb
<p>
    Yaniv What do you think? <%= @title %>

      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
</p>

app/views/pages/about.html.erb
<h1>Yaniv What do you think? <%= @title %></h1>

<p>
   
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
</p>

app/views/pages/activities.html.erb
<p>
    Yaniv What do you think? <%= @title %>

      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
</p>

app/views/pages/home.html.erb
<h1><%= @title %></h1>

<p>
   
     <% if signed_in? %>
      Sign in User
     <% else %>
        <%= link_to "Sign in", signin_path %>
     
        <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
     <% end %>

</p>

app/views/pages/myaccount.html.erb
<p>
    <h1>Yaniv What do you think? <%= @title %></h1>

      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
</p>

app/views/pages/myteam.html.erb
<p>
    <h1>Yaniv What do you think? <%= @title %></h1>

      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
</p>

app/views/pages/signout.html.erb
<h1>Yaniv What do you think? <%= @title %></h1>

<p>
   
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
</p>