config/routes.rb
FirstApp::Application.routes.draw do
  
  resources :users
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :activities, :only => [:create, :destroy, :allactivities]

  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

resources :pages  
  
  match '/about',   :to => 'pages#about'
  match '/home',    :to => 'pages#home'
  match '/signout',   :to => 'pages#signout'
  match '/myteam',   :to => 'pages#myteam'
 
  match '/help',    :to => 'pages#help'
   match '/contact', :to => 'pages#contact'
  match '/myaccount', :to => 'pages#myaccount'
  

  get "pages/signout"

  
  
  
  
  resources :users
  get "users/show"
  match '/signup',  :to => 'users#new'
  match '/allusers',  :to => 'users#allusers'
  
  
  
  

   root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
           <table border="0" cellpadding="8" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" bgcolor="#000000">
          <tr>
            <!--td><a href="/home"><%= image_tag("tivity.jpg", :alt => "Tivity", :width =>"100", :height => "40") %></td-->
           <td>   <%= link_to logo, root_path %></td>
         
            <td bgcolor="#FFFFFF" valign="bottom">
            <!--%= link_to "Home", home_path %-->
            <p align="left">
            <font face="Arial" color="#999999" style="font-size: 8pt">get things 
            done.&nbsp; <br>
            together.</font>
            </td>
          </tr>
          
          
          
          <tr>
           <nav class="round">
              
              <ul>
                
               <% if signed_in? %>
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Users", allusers_path %></li> 
               
               <% end %>
                
                <li><%= link_to "Help", help_path %></li>
                <% if signed_in? %>
                  <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
                <% else %>
                  <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
              </ul>
        </nav>
        </tr>
        
        
        
        
        
        
        </table>   
          <table border="0" cellpadding="6" cellspacing="0" style="border-collapse: collapse" width="100%" bgcolor="#333333">
              <tr>
                <td width="11%" align="center">
                <table border="1" cellpadding="2" cellspacing="0" style="border-collapse: collapse" width="90%" bordercolor="#CCFF99">
                  <tr>
                    <td width="100%">
                    <p align="center"><b>
                    <font face="Arial" size="2" color="#CCFF99"> <li><%= link_to "Home", root_path %></li>
               </font></b></td>
                  </tr>
                </table>
                </td>
                <td width="11%" align="center">
                <font face="Arial" size="2" color="#FFFFFF">all activities</font></td>
                <td width="11%" align="center">
                <font face="Arial" size="2" color="#FFFFFF">my team</font></td>
                <td width="11%" align="center">&nbsp;</td>
                <td width="11%" align="center">&nbsp;</td>
                <td width="11%" align="center">&nbsp;</td>
                <td width="11%" align="center">&nbsp;</td>
                <td width="11%" align="center">&nbsp;</td>
                <td width="12%" align="center">&nbsp;</td>
              </tr>
            </table>     
   </header>
     

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %> </title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
    
  </head>
  
<body>
    <div class="container">
      
      <%= render 'layouts/header' %>
      
       <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      
      
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>    
</body>

  
</html>